version: '3'

tasks:
  default:
    cmds:
      - echo Usage task dev project=PROJECT_NAME
      - yarn parcel build {{.TASKFILE_DIR}}/challenges/{{.project}}/*.pug --dist-dir {{.TASKFILE_DIR}}/challenges/{{.project}}/dist/ --no-source-maps --no-content-hash --no-optimize

  dev:
    cmds:
      - yarn parcel {{.TASKFILE_DIR}}/challenges/{{.project}}/index.pug --dist-dir {{.TASKFILE_DIR}}/challenges/{{.project}}/dist --no-source-maps
